### ISSUE TITLE
Make initially open panel configurable in single select mode

### ISSUE THREAD

**Issue by mspae** [mynamesleon/aria-tablist#21]
Right now this is always the panel with index `0`.

Would you be willing to accept a MR for this?

**Comment by mynamesleon** [comment]
Hi @mspae.

I don't quite understand the request. You can use `aria-selected="true"` or `data-selected="true"` on the tab element that you want to be active initially, and the code will then display the corresponding panel and hide the others. So this is already configurable.

**Comment by mspae** [comment]
Good point. I didn't think of that! Thanks for the heads up!

I'll close the issue now since this is good enough for me. ;)
