### ISSUE TITLE
Typescript definitions not included in npm package

### ISSUE THREAD

**Issue by andrejpavlovic** [mynamesleon/aria-tablist#3]
I'm trying to use this in my typescript project, but npm install doesn't include typescript definitions. I can put together a pull request, if that's alright with you?

**Comment by mynamesleon** [comment]
Sorry for the delay in dealing with this. The past few months have been a bit crazy, and I hadn't actually logged into this account for a while. I've merged an update, and published a new version (1.2.1) to npm for this.

**Comment by andrejpavlovic** [comment]
Thanks for an update on this. I tried the latest version, but it's not working well for me. I think it's an issue with how the class is declared ie, it's declared as a function as opposed to as a class, so "new" doesn't work.

On something like
```typescript
import AriaTablist from 'aria-tablist'
const tablist = new AriaTablist(el)
```

I get error `'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.ts(7009)`

**Comment by mynamesleon** [comment]
There is a `Tablist` class that's used internally, but the `AriaTablist` call that's exposed is just a normal function. So it can technically be called with the `new` keyword, but it isn't necessary.

**Comment by andrejpavlovic** [comment]
Seems to work without the `new` keyword, but in the readme it says to use it with the `new` keyword. Makes it a bit confusing for typescript users like myself.

**Comment by mynamesleon** [comment]
Yes that's my mistake! I updated the examples page to not use `new`, but forgot to update the readme. Sorry about that. I'm not actually sure how to define it in the types file to allow both uses. I'll see if I can do that, but I'll at least update the readme for now.
