### ISSUE TITLE
Make possible to select tablists with querySelectorAll

### ISSUE THREAD

**Issue by hotgeart** [mynamesleon/aria-tablist#5]
Hi @mynamesleon,

In case we've multiple tablists in a page `querySelectorAll` should works IMO:

demo: https://jsfiddle.net/y32hLbw4/1/

```
AriaTablist(document.querySelectorAll('.tablist'));
```

**Comment by mynamesleon** [comment]
Sorry for my delayed reply. The email for this got buried!

It _could_, however, the `AriaTablist` function returns an API instance for that specific tablist. Your example code may not make use of that, but the returned API is a key part of being able to update the tablist programmatically (as it exposes methods to open, close, or delete specific tabs). I especially make use of the `destroy` method for when the tablist is removed from the DOM.

If I made a change to be able to receive multiple elements as the first param, it could either return an array of API instances, or nothing. But I'd much prefer to keep it consistent and always return a single API instance for a single element.

If you're using a modern toolset, you can easily loop through and call the tablist for each element. And if you need an array of the resulting API instances, that's doable with one line of code as well. e.g.

```js
const instances = [...document.querySelectorAll('.tablist')].map((tablist) => AriaTablist(tablist));
```
